Fix simulation
invariant-labs/webapp pull request #138
Opened 2022-02-01 10:07 UTC by PawelKrawczyk96

2022-02-01 10:49 UTC, wojciech-cichocki approved these changes

2022-02-01 14:01 UTC, awojciak commented on src/components/Swap/Swap.tsx
> +      return 'insufficient volume'
Use capital letters on start of sentences

2022-02-01 14:05 UTC, awojciak reviewed
![obraz](https://user-images.githubusercontent.com/48929607/151982921-024d532a-009f-4bfc-8706-b2171ed2136a.png)
exchange rate is still wrong

2022-02-01 14:13 UTC, wojciech-cichocki requested changes

2022-02-02 09:53 UTC, wojciech-cichocki commented
Here should be "exceed single swap limit" error:
![Screenshot from 2022-02-02 10-52-08](https://user-images.githubusercontent.com/43304803/152131302-debaeedd-919f-4750-98e9-b151d2249639.png)

2022-02-02 10:15 UTC, wojciech-cichocki approved these changes

2022-02-02 10:16 UTC, merged