New swap design
invariant-labs/webapp pull request #147
Opened 2022-02-08 08:20 UTC by luckmer

2022-02-08 08:51 UTC, PawelKrawczyk96 requested changes

2022-02-08 08:51 UTC, PawelKrawczyk96 commented on src/components/Inputs/ExchangeAmountInput/style.ts
> +    fontWeight: 'bold',
Try to use out newTypography object to set font.

2022-02-08 08:51 UTC, PawelKrawczyk96 commented on src/components/Inputs/ExchangeAmountInput/style.ts
> +    fontSize: 12,
same like above

2022-02-08 08:51 UTC, PawelKrawczyk96 commented on src/components/Inputs/ExchangeAmountInput/style.ts
> +    fontSize: '12px',
try to use newTypography

2022-02-08 08:51 UTC, PawelKrawczyk96 commented on src/components/Swap/style.ts
> +    // backgroundColor: colors.invariant.componentIn2
if these comments are not needed, please remove it

2022-02-08 08:52 UTC, PawelKrawczyk96 commented
![image](https://user-images.githubusercontent.com/37472310/152951437-ae79c0ae-cf2a-4d6d-9806-f6876d0355c6.png)
this space between select and balance component is too high, check it on figma

2022-02-08 08:53 UTC, PawelKrawczyk96 commented
![image](https://user-images.githubusercontent.com/37472310/152951695-47ecc421-0d4d-41b1-a43e-affd765cfab7.png)
padding bottom is to high

2022-02-08 08:55 UTC, PawelKrawczyk96 commented
![Uploading image.png…]()
too high padding between input-transaction details-connect button.
Also the button color is different

2022-02-08 09:34 UTC, PawelKrawczyk96 commented
![image](https://user-images.githubusercontent.com/37472310/152958873-13ab416c-9f60-40df-891d-673e26291dca.png)
amount should be in right side of input

2022-02-08 09:36 UTC, PawelKrawczyk96 commented
![image](https://user-images.githubusercontent.com/37472310/152959082-98ce3c43-3340-4a90-98da-230840747b1c.png)
if error meaning we couldn't swap tokens, button should be disabled (last view on figma in swap)

2022-02-08 09:41 UTC, PawelKrawczyk96 commented
![image](https://user-images.githubusercontent.com/37472310/152960114-c2a4d050-bf5e-471b-b417-4d0d0f739a8c.png)
you have other 2 components to change in new design. Check it on Storybook and change it.

2022-02-08 09:46 UTC, PawelKrawczyk96 commented
![Uploading image.png…]()
this color is wrong, additionally hover on this component is different. (also change cursor on it)

2022-02-08 10:00 UTC, PawelKrawczyk96 commented
![image](https://user-images.githubusercontent.com/37472310/152963940-2fae9113-bb27-4964-832c-fafe027d46a7.png)
this icons has wrong color

2022-02-08 10:03 UTC, PawelKrawczyk96 commented
![image](https://user-images.githubusercontent.com/37472310/152964184-45ba8058-3ce2-49a5-9d8e-2f41a50460ba.png)
arrow icon is a little bit smaller. Also padding between name and icon is smaller than on figma

2022-02-08 10:06 UTC, awojciak commented on src/components/AnimatedButton/style.ts
> +    background: colors.invariant.greenLinearGradient,
are you sure this won't affect any other places, where this animated button is used?

2022-02-08 10:06 UTC, PawelKrawczyk96 commented
![image](https://user-images.githubusercontent.com/37472310/152965064-2bc6d686-2c1a-48d0-815f-594b7e621b5a.png)
maybe we make this icon a little bigger than this.

2022-02-08 10:06 UTC, awojciak commented on src/components/Inputs/ExchangeAmountInput/ExchangeAmountInput.tsx
> +  Balance?: string | undefined
props' names should be lowercased

2022-02-08 10:10 UTC, awojciak commented on src/components/Swap/Swap.tsx
> -import TransactionDetails from '@components/Swap/transactionDetails/TransactionDetails'
why are you not using that anymore?

2022-02-08 10:14 UTC, awojciak commented on src/components/Inputs/ExchangeAmountInput/ExchangeAmountInput.tsx
> +      <Box className={classes.container}>
about data that should be shown at bottom of the input: look at the input used in new position view in don it in similar way

2022-02-08 10:18 UTC, awojciak requested changes
also:
1) 
![obraz](https://user-images.githubusercontent.com/48929607/152966691-9c8843f2-49a1-4888-a5ec-297e52fae024.png)
this modal is not adjusted to new design
2) 
![obraz](https://user-images.githubusercontent.com/48929607/152966920-b21150c2-58fe-49ad-aa4b-b9edb6322df9.png)
that's how should disabled button look, I don't know why there happened an inconsistency in mockups
3) 
![obraz](https://user-images.githubusercontent.com/48929607/152967118-0f17fc69-fca2-43e5-9090-b377bc55735c.png)
that looks ugly on mobile resolutions
4) because of change in animated button, button used in new position view has wrong styles

2022-02-09 11:08 UTC, awojciak commented on src/components/AnimatedButton/AnimatedButton.tsx
> +          content === 'Connect a wallet' && classes.buttonSelectDisabled,
instead of hardcoding special cases use className prop where you're using that component and set styles through this

2022-02-09 11:22 UTC, awojciak requested changes
1) 
![obraz](https://user-images.githubusercontent.com/48929607/153187468-48b2bb76-0847-45cc-b852-2bcb69e27b1c.png)
just show single "No data"
2) 
![obraz](https://user-images.githubusercontent.com/48929607/153187719-891dcb4c-8d79-49ec-a3f7-2da8f4d3532c.png)
how it should look: 
![obraz](https://user-images.githubusercontent.com/48929607/153187973-b1241ddf-3796-4bed-84c3-231b922d67b5.png)
3) progress bar animation in new position view is not visible, fix this
4) 
![obraz](https://user-images.githubusercontent.com/48929607/153188953-a0404960-5b82-4371-883a-7ec592e23398.png)
i don't think this looks good, talk with Agnieszka about colors for animation
5) 
![obraz](https://user-images.githubusercontent.com/48929607/153189473-36a365c8-324d-4c10-8664-00f97cf492b0.png)
I think that color of text in this input should be lighter
6) animation on clicking arrows button (inputs "swapping" places) works only every second click
7) 
![obraz](https://user-images.githubusercontent.com/48929607/153189867-2688fa6a-db25-450e-9837-937e734224cc.png)
distance between icon and text seems to be too small
8) 
![obraz](https://user-images.githubusercontent.com/48929607/153190019-8cd12db6-9a7b-4d1e-8cf7-e944465a9935.png)
enlarge this button to have min-width like on mockups

2022-02-09 16:09 UTC, awojciak commented on src/components/Swap/style.ts
> +    '& :hover': {
tip: use &:hover $transactionDetailsInfo' to flatten structure

2022-02-09 16:14 UTC, awojciak commented on src/components/OutlinedButton/style.ts
> +    widt: 20,
width

2022-02-09 16:15 UTC, awojciak commented on src/components/OutlinedButton/OutlinedButton.tsx
> +        !isNaN(Number(balance)) && classes.activeButton,
set these styles through className prop; what if this component will be used somewhere, where there will be no such thing as 'balance'?

2022-02-09 16:16 UTC, awojciak commented on src/components/Modals/SelectModals/style.ts
> +    background: '#ef84f5',
use colors from theme

2022-02-09 16:18 UTC, awojciak commented on src/components/AnimatedButton/AnimatedButton.tsx
> +  const getContent = () => {
move this to swap and set class through className prop; also template strings are not necessary there

2022-02-09 16:31 UTC, awojciak requested changes
1) 
![obraz](https://user-images.githubusercontent.com/48929607/153243981-fbf2d3d4-17cc-4d5c-8f6e-a47a4fbc814b.png)
select button should be longer, also max button shouldn't hide; balance should be in one line with 'No data'
2) it should be 'Max', not 'MAX'
3) clicking on transaction details button on mobile resolution does nothing, modal doesn't show
4) on mobile resolution transaction details button is changing its height when inputs are changed
5) when typing something in upper input, first typed digit doesn't show in input
6) 
![obraz](https://user-images.githubusercontent.com/48929607/153245224-c958ee7a-ba6a-4989-9604-5d9c733e4ba8.png)
why there are no balances?
7) 
![obraz](https://user-images.githubusercontent.com/48929607/153245351-9baaf45e-c354-44be-9f6f-9635933dbe6f.png)
modal doesn't look like on mockup

2022-02-10 12:58 UTC, awojciak commented on src/components/AnimatedButton/AnimatedButton.tsx
> +  classNameContent: string
is it really necessary to duplicate className prop instead of simply using it?

2022-02-10 13:01 UTC, awojciak commented on src/static/theme.ts
> +    lightPink: '#ef84f5',
you're duplicating here color from line 83

2022-02-10 13:09 UTC, Pawel-Szydlo reviewed
![image](https://user-images.githubusercontent.com/89639506/153413934-bd543e2f-ed53-4d83-b6d5-e6ba972b3e02.png)
- hover doesn't match and fontSize is too small

2022-02-10 13:11 UTC, awojciak requested changes
1) 
![obraz](https://user-images.githubusercontent.com/48929607/153413870-660e958d-9f42-437c-8acf-0fd83a608635.png)
fix this, list shows only when wallet is connnected
2)
![obraz](https://user-images.githubusercontent.com/48929607/153414114-0c644cf5-05c7-4dd9-bd06-962225d38386.png)
scroll is not working
3) 
![obraz](https://user-images.githubusercontent.com/48929607/153414312-c9835311-5b8c-4810-a7b1-6e414b9ca6c4.png)
here when hovering X, black rectangle is showing behind it
4) 
![obraz](https://user-images.githubusercontent.com/48929607/153414579-615e3e17-a0a6-48f8-a8e6-54c1f6f8ef14.png)
height of this element is changing when loading happens
5) 
![obraz](https://user-images.githubusercontent.com/48929607/153414888-221cb3bb-91fa-4256-9720-93b3d19bf21c.png)
width of modal is too big in this case

2022-02-10 15:51 UTC, awojciak commented on src/components/Inputs/ExchangeAmountInput/ExchangeAmountInput.tsx
> +              disabled && isNaN(Number(balance))
why 'isNaN(Number(balance))' is used as condition to disable input?

2022-02-10 15:54 UTC, awojciak requested changes
also:
1) mockup: 
![obraz](https://user-images.githubusercontent.com/48929607/153444667-90b94402-1e85-4030-95b9-39bdbf97ca51.png)
app: 
![obraz](https://user-images.githubusercontent.com/48929607/153444727-5b83cdda-3865-4d97-9870-6f16b1c9789a.png)
2) app: 
![obraz](https://user-images.githubusercontent.com/48929607/153444792-689aed50-cd89-400d-94c1-523d02d6ce2a.png)
mockup: 
![obraz](https://user-images.githubusercontent.com/48929607/153444957-ab2a185e-9eaa-4d4b-afbd-7e711ad2233c.png)
3) mockup: 
![obraz](https://user-images.githubusercontent.com/48929607/153445032-051e8cea-c606-4316-a432-b83555f82784.png)
app: 
![obraz](https://user-images.githubusercontent.com/48929607/153445111-512754d4-fff0-4f5b-bebf-05557a285c79.png)
adjust these components

2022-02-11 10:50 UTC, merged

2022-02-11 11:04 UTC, NorbertBodziony commented
![image](https://user-images.githubusercontent.com/38857779/153580935-106832fb-848c-43e8-88d4-5abec012a8bc.png)
Hover does not work as intended + incorrect design.

2022-02-11 11:15 UTC, NorbertBodziony commented on src/components/AnimatedButton/style.ts
>      }
Do you know why we use `!important` ?

2022-02-11 11:15 UTC, NorbertBodziony commented on src/components/Inputs/ExchangeAmountInput/style.ts
> +    }
Come on. This is BS. We use material ui so you dont have to deal with selectors.

2022-02-11 11:15 UTC, NorbertBodziony commented on src/components/Inputs/ExchangeAmountInput/style.ts
> +      filter: 'brightness(1.1)'
brightness^2 ? Do not use brightness at all. This can be easy solved without it!

2022-02-11 11:15 UTC, NorbertBodziony commented on src/components/Inputs/Select/style.ts
>      },
I dont want to see any `brightness` at all

2022-02-11 11:15 UTC, NorbertBodziony commented on src/components/Inputs/Select/style.ts
>      fontFamily: 'Mukta',
Random new font ?

2022-02-11 11:15 UTC, NorbertBodziony commented on src/components/Swap/style.ts
> +    }
Do not use brightness

2022-02-11 11:15 UTC, NorbertBodziony commented on src/components/Swap/style.ts
> +      boxShadow:
brightness hell