Bond list
invariant-labs/webapp pull request #281
Opened 2022-04-04 06:57 UTC by mariuszk98

2022-04-04 11:08 UTC, awojciak commented on src/components/Bonds/BondList/BondList.stories.tsx
> +    const [data] = React.useState(
useState is unnecessary here, data is not changing

2022-04-04 11:09 UTC, awojciak commented on src/components/Bonds/BondItem/BondItem.tsx
> +        <>
fragments are not necessary if there is only one node on top level

2022-04-04 11:09 UTC, awojciak commented on src/components/Bonds/BondItem/BondItem.tsx
> +        <></>
just use null

2022-04-05 06:34 UTC, PawelKrawczyk96 commented
![image](https://user-images.githubusercontent.com/37472310/161693090-7f0952c2-dd0d-4af7-bd89-4d0673dc3f2c.png)
maybe move pair column to the left below 600px , ROI don't have space a little

2022-04-05 06:44 UTC, PawelKrawczyk96 requested changes

2022-04-05 06:44 UTC, PawelKrawczyk96 commented on src/components/Bonds/BondItem/BondItem.tsx
> +interface BondItem {
change name to IBondItem (interfaces have 'I' on the beginning)

2022-04-05 10:15 UTC, awojciak requested changes
1) fix remaining lint issues
2) storybook: 
![obraz](https://user-images.githubusercontent.com/48929607/161731991-452c6f17-51b1-4867-815d-5b312afaba09.png)
mockup:
![obraz](https://user-images.githubusercontent.com/48929607/161732050-fd7c54a5-22b1-48a0-b69a-4bb497e7a7e2.png)
3) 
![obraz](https://user-images.githubusercontent.com/48929607/161732123-52363b89-9ae5-4812-91c8-1d90007c2b16.png)
there is something wrong with font

2022-04-06 12:00 UTC, awojciak requested changes
1) there is still no gradient in button
2) https://www.figma.com/file/LsofkIRxZQIgGo1p18raOy/App?node-id=2905%3A7815 - hover on button doesn't look like that in storybook, fix this
3) 
![obraz](https://user-images.githubusercontent.com/48929607/161969882-03fbe586-a7c6-4d6a-b5ee-d0bf804926a7.png)
i think header and content in this column should be centered

2022-04-07 12:40 UTC, awojciak approved these changes

2022-04-08 06:02 UTC, merged