Single position page
invariant-labs/webapp pull request #36
Opened 2021-12-03 15:40 UTC by awojciak

2021-12-03 21:12 UTC, wojciech-cichocki requested changes
Sometimes after closing position, UI show that I have no position, but I still have a few. It will fix after refreshing the page.

![Screenshot from 2021-12-03 22-04-21](https://user-images.githubusercontent.com/43304803/144672757-eedf0c9f-87fc-4d86-8d07-30b10cf0d5dd.png)

2021-12-13 09:44 UTC, wojciech-cichocki commented
unclaimed fees simulation:
![Screenshot from 2021-12-13 10-32-04](https://user-images.githubusercontent.com/43304803/145788800-c108c7ca-a45f-47f4-a8db-6a1fc2d78923.png)

2021-12-13 09:44 UTC, wojciech-cichocki commented
Negative liquidity:
![Screenshot from 2021-12-13 10-39-05](https://user-images.githubusercontent.com/43304803/145788911-bdc8ad2b-6310-4796-8df7-3e922fc0c59e.png)

2021-12-13 13:04 UTC, PawelKrawczyk96 requested changes
other coments below

2021-12-13 13:07 UTC, PawelKrawczyk96 commented
![image](https://user-images.githubusercontent.com/37472310/145817637-2f1fc9a8-3db7-4a02-a9f2-4027a66218c2.png)
This button should be more wider (on position details)

2021-12-13 13:10 UTC, PawelKrawczyk96 commented
![image](https://user-images.githubusercontent.com/37472310/145818086-bb9c69c8-7824-4ceb-b3dd-74eed1619a53.png)
this header is a little bit lower than plot component

2021-12-13 13:10 UTC, PawelKrawczyk96 commented
claim fee button have wrong color on hover state.

2021-12-13 13:14 UTC, PawelKrawczyk96 commented
![image](https://user-images.githubusercontent.com/37472310/145818991-7915609d-36ab-41c8-9ede-cbe9f1bff0b2.png)
this hover state is not consistent with figma.

2021-12-13 13:35 UTC, awojciak commented on src/containers/NewPositionWrapper/NewPositionWrapper.tsx
> +        console.log('pool token x:', allPools[poolIndex].tokenX.toString())
I'm gonna leave these by now, Konrad is using them

2021-12-14 15:17 UTC, merged