Plots lazy loading
invariant-labs/webapp pull request #65
Opened 2021-12-22 12:11 UTC by awojciak

2021-12-22 12:22 UTC, wojciech-cichocki reviewed
Maybe we should add information that chart is still loading and this information not block chart?

2021-12-22 13:00 UTC, PawelKrawczyk96 commented
![image](https://user-images.githubusercontent.com/37472310/147096515-9f4fc61c-5801-4b84-9ef9-3a2568ce8834.png)
Maybe you add some loading animation with small blur on plot. In my opinion, user doesn't know it is lazy loading.

2021-12-22 13:01 UTC, PawelKrawczyk96 requested changes
comment above

2021-12-23 09:34 UTC, PawelKrawczyk96 approved these changes

2021-12-23 09:40 UTC, merged